// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TargetUser {
    #[prost(oneof = "target_user::User", tags = "1")]
    pub user: ::core::option::Option<target_user::User>,
}
/// Nested message and enum types in `TargetUser`.
pub mod target_user {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum User {
        #[prost(string, tag = "1")]
        UserToken(::prost::alloc::string::String),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthCheckRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthCheckResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartAuthSessionRequest {
    #[prost(string, tag = "1")]
    pub client_state: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartAuthSessionResponse {
    #[prost(string, tag = "1")]
    pub session_code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub login_url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAuthSessionRequest {
    #[prost(string, tag = "1")]
    pub session_code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub client_state: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAuthSessionResponse {
    #[prost(message, optional, tag = "1")]
    pub user_token: ::core::option::Option<UserToken>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RefreshAuthSessionRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RefreshAuthSessionResponse {
    #[prost(message, optional, tag = "1")]
    pub user_token: ::core::option::Option<UserToken>,
}
/// Verify the target is compliant with the given Product Name as registered in `ucs-auth-api` config
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyCompliance {
    #[prost(string, tag = "1")]
    pub product_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyRequirement {
    #[prost(oneof = "verify_requirement::Requirement", tags = "2")]
    pub requirement: ::core::option::Option<verify_requirement::Requirement>,
}
/// Nested message and enum types in `VerifyRequirement`.
pub mod verify_requirement {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Requirement {
        #[prost(message, tag = "2")]
        Compliance(super::VerifyCompliance),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyUserRequest {
    #[prost(message, optional, tag = "1")]
    pub target_user: ::core::option::Option<TargetUser>,
    #[prost(message, repeated, tag = "2")]
    pub requirements: ::prost::alloc::vec::Vec<VerifyRequirement>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyUserResponse {
    #[prost(message, optional, tag = "1")]
    pub user_info: ::core::option::Option<UserInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExchangeExternalTokenForUserTokenRequest {
    #[prost(string, tag = "1")]
    pub external_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExchangeExternalTokenForUserTokenResponse {
    #[prost(message, optional, tag = "1")]
    pub user_token: ::core::option::Option<UserToken>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExchangeApiKeyForUserTokenRequest {
    #[prost(string, tag = "1")]
    pub api_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExchangeApiKeyForUserTokenResponse {
    #[prost(message, optional, tag = "1")]
    pub user_token: ::core::option::Option<UserToken>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserToken {
    #[prost(string, tag = "1")]
    pub user_token: ::prost::alloc::string::String,
    /// Epoch
    #[prost(int64, tag = "2")]
    pub expires_at: i64,
    /// URC user ID
    #[prost(string, tag = "3")]
    pub user_id: ::prost::alloc::string::String,
    /// Display name
    #[prost(string, tag = "4")]
    pub user_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResourcePermission {
    #[prost(string, tag = "1")]
    pub resource_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub permission: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExchangeUserTokenForMultiresourceTokenRequest {
    #[prost(string, repeated, tag = "1")]
    pub resource_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExchangeUserTokenForMultiresourceTokenResponse {
    #[prost(message, optional, tag = "1")]
    pub token: ::core::option::Option<UserToken>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckUserPermissionRequest {
    #[prost(string, repeated, tag = "1")]
    pub resource_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "2")]
    pub target_user: ::core::option::Option<TargetUser>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckUserPermissionResponse {
    #[prost(message, repeated, tag = "1")]
    pub allowed_resource_permission: ::prost::alloc::vec::Vec<ResourcePermission>,
    #[prost(message, repeated, tag = "2")]
    pub denied_resource_permission: ::prost::alloc::vec::Vec<ResourcePermission>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LookupUserPermissionsRequest {
    #[prost(string, tag = "1")]
    pub resource_filter: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub context_filter: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "3")]
    pub page_size: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "4")]
    pub page_token: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LookupUserPermissionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub resource_permission: ::prost::alloc::vec::Vec<ResourcePermission>,
    #[prost(string, optional, tag = "2")]
    pub next_page_token: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserInfoRequest {
    #[prost(string, tag = "1")]
    pub resource_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub user_id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserInfo {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub display_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserInfoResponse {
    #[prost(message, repeated, tag = "1")]
    pub user_info: ::prost::alloc::vec::Vec<UserInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserIdRequest {
    #[prost(string, tag = "1")]
    pub resource_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_display_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserIdResponse {
    #[prost(message, optional, tag = "1")]
    pub user_info: ::core::option::Option<UserInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProviderUserIdRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProviderUserIdResponse {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub provider_user_id: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod urc_auth_api_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct UrcAuthApiClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl UrcAuthApiClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> UrcAuthApiClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> UrcAuthApiClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            UrcAuthApiClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn health_check(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/HealthCheck",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "HealthCheck"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn start_auth_session(
            &mut self,
            request: impl tonic::IntoRequest<super::StartAuthSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StartAuthSessionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/StartAuthSession",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "StartAuthSession"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_auth_session(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAuthSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAuthSessionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/GetAuthSession",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "GetAuthSession"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn refresh_auth_session(
            &mut self,
            request: impl tonic::IntoRequest<super::RefreshAuthSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RefreshAuthSessionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/RefreshAuthSession",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "RefreshAuthSession"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn verify_user(
            &mut self,
            request: impl tonic::IntoRequest<super::VerifyUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::VerifyUserResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/VerifyUser",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "VerifyUser"));
            self.inner.unary(req, path, codec).await
        }
        /// For external authentication token login
        pub async fn exchange_external_token_for_user_token(
            &mut self,
            request: impl tonic::IntoRequest<
                super::ExchangeExternalTokenForUserTokenRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<super::ExchangeExternalTokenForUserTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/ExchangeExternalTokenForUserToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "epic_urc.UrcAuthApi",
                        "ExchangeExternalTokenForUserToken",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// For API key login
        pub async fn exchange_api_key_for_user_token(
            &mut self,
            request: impl tonic::IntoRequest<super::ExchangeApiKeyForUserTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExchangeApiKeyForUserTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/ExchangeAPIKeyForUserToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("epic_urc.UrcAuthApi", "ExchangeAPIKeyForUserToken"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// For token exchange
        pub async fn exchange_user_token_for_multiresource_token(
            &mut self,
            request: impl tonic::IntoRequest<
                super::ExchangeUserTokenForMultiresourceTokenRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<super::ExchangeUserTokenForMultiresourceTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/ExchangeUserTokenForMultiresourceToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "epic_urc.UrcAuthApi",
                        "ExchangeUserTokenForMultiresourceToken",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// For permission checks
        pub async fn check_user_permission(
            &mut self,
            request: impl tonic::IntoRequest<super::CheckUserPermissionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckUserPermissionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/CheckUserPermission",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "CheckUserPermission"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn lookup_user_permissions(
            &mut self,
            request: impl tonic::IntoRequest<super::LookupUserPermissionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LookupUserPermissionsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/LookupUserPermissions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "LookupUserPermissions"));
            self.inner.unary(req, path, codec).await
        }
        /// User metadata
        pub async fn get_user_info(
            &mut self,
            request: impl tonic::IntoRequest<super::GetUserInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUserInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/GetUserInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "GetUserInfo"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_user_id(
            &mut self,
            request: impl tonic::IntoRequest<super::GetUserIdRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUserIdResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/GetUserId",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "GetUserId"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_provider_user_id(
            &mut self,
            request: impl tonic::IntoRequest<super::GetProviderUserIdRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetProviderUserIdResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/epic_urc.UrcAuthApi/GetProviderUserId",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("epic_urc.UrcAuthApi", "GetProviderUserId"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod urc_auth_api_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with UrcAuthApiServer.
    #[async_trait]
    pub trait UrcAuthApi: std::marker::Send + std::marker::Sync + 'static {
        async fn health_check(
            &self,
            request: tonic::Request<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        >;
        async fn start_auth_session(
            &self,
            request: tonic::Request<super::StartAuthSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StartAuthSessionResponse>,
            tonic::Status,
        >;
        async fn get_auth_session(
            &self,
            request: tonic::Request<super::GetAuthSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAuthSessionResponse>,
            tonic::Status,
        >;
        async fn refresh_auth_session(
            &self,
            request: tonic::Request<super::RefreshAuthSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RefreshAuthSessionResponse>,
            tonic::Status,
        >;
        async fn verify_user(
            &self,
            request: tonic::Request<super::VerifyUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::VerifyUserResponse>,
            tonic::Status,
        >;
        /// For external authentication token login
        async fn exchange_external_token_for_user_token(
            &self,
            request: tonic::Request<super::ExchangeExternalTokenForUserTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExchangeExternalTokenForUserTokenResponse>,
            tonic::Status,
        >;
        /// For API key login
        async fn exchange_api_key_for_user_token(
            &self,
            request: tonic::Request<super::ExchangeApiKeyForUserTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExchangeApiKeyForUserTokenResponse>,
            tonic::Status,
        >;
        /// For token exchange
        async fn exchange_user_token_for_multiresource_token(
            &self,
            request: tonic::Request<super::ExchangeUserTokenForMultiresourceTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExchangeUserTokenForMultiresourceTokenResponse>,
            tonic::Status,
        >;
        /// For permission checks
        async fn check_user_permission(
            &self,
            request: tonic::Request<super::CheckUserPermissionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckUserPermissionResponse>,
            tonic::Status,
        >;
        async fn lookup_user_permissions(
            &self,
            request: tonic::Request<super::LookupUserPermissionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LookupUserPermissionsResponse>,
            tonic::Status,
        >;
        /// User metadata
        async fn get_user_info(
            &self,
            request: tonic::Request<super::GetUserInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUserInfoResponse>,
            tonic::Status,
        >;
        async fn get_user_id(
            &self,
            request: tonic::Request<super::GetUserIdRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUserIdResponse>,
            tonic::Status,
        >;
        async fn get_provider_user_id(
            &self,
            request: tonic::Request<super::GetProviderUserIdRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetProviderUserIdResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct UrcAuthApiServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> UrcAuthApiServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for UrcAuthApiServer<T>
    where
        T: UrcAuthApi,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/epic_urc.UrcAuthApi/HealthCheck" => {
                    #[allow(non_camel_case_types)]
                    struct HealthCheckSvc<T: UrcAuthApi>(pub Arc<T>);
                    impl<
                        T: UrcAuthApi,
                    > tonic::server::UnaryService<super::HealthCheckRequest>
                    for HealthCheckSvc<T> {
                        type Response = super::HealthCheckResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthCheckRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UrcAuthApi>::health_check(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthCheckSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/epic_urc.UrcAuthApi/StartAuthSession" => {
                    #[allow(non_camel_case_types)]
                    struct StartAuthSessionSvc<T: UrcAuthApi>(pub Arc<T>);
                    impl<
                        T: UrcAuthApi,
                    > tonic::server::UnaryService<super::StartAuthSessionRequest>
                    for StartAuthSessionSvc<T> {
                        type Response = super::StartAuthSessionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StartAuthSessionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UrcAuthApi>::start_auth_session(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StartAuthSessionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/epic_urc.UrcAuthApi/GetAuthSession" => {
                    #[allow(non_camel_case_types)]
                    struct GetAuthSessionSvc<T: UrcAuthApi>(pub Arc<T>);
                    impl<
                        T: UrcAuthApi,
                    > tonic::server::UnaryService<super::GetAuthSessionRequest>
                    for GetAuthSessionSvc<T> {
                        type Response = super::GetAuthSessionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAuthSessionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UrcAuthApi>::get_auth_session(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAuthSessionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/epic_urc.UrcAuthApi/RefreshAuthSession" => {
                    #[allow(non_camel_case_types)]
                    struct RefreshAuthSessionSvc<T: UrcAuthApi>(pub Arc<T>);
                    impl<
                        T: UrcAuthApi,
                    > tonic::server::UnaryService<super::RefreshAuthSessionRequest>
                    for RefreshAuthSessionSvc<T> {
                        type Response = super::RefreshAuthSessionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RefreshAuthSessionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UrcAuthApi>::refresh_auth_session(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RefreshAuthSessionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/epic_urc.UrcAuthApi/VerifyUser" => {
                    #[allow(non_camel_case_types)]
                    struct VerifyUserSvc<T: UrcAuthApi>(pub Arc<T>);
                    impl<
                        T: UrcAuthApi,
                    > tonic::server::UnaryService<super::VerifyUserRequest>
                    for VerifyUserSvc<T> {
                        type Response = super::VerifyUserResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::VerifyUserRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UrcAuthApi>::verify_user(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = VerifyUserSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/epic_urc.UrcAuthApi/ExchangeExternalTokenForUserToken" => {
                    #[allow(non_camel_case_types)]
                    struct ExchangeExternalTokenForUserTokenSvc<T: UrcAuthApi>(
                        pub Arc<T>,
                    );
                    impl<
                        T: UrcAuthApi,
                    > tonic::server::UnaryService<
                        super::ExchangeExternalTokenForUserTokenRequest,
                    > for ExchangeExternalTokenForUserTokenSvc<T> {
                        type Response = super::ExchangeExternalTokenForUserTokenResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::ExchangeExternalTokenForUserTokenRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UrcAuthApi>::exchange_external_token_for_user_token(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExchangeExternalTokenForUserTokenSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/epic_urc.UrcAuthApi/ExchangeAPIKeyForUserToken" => {
                    #[allow(non_camel_case_types)]
                    struct ExchangeAPIKeyForUserTokenSvc<T: UrcAuthApi>(pub Arc<T>);
                    impl<
                        T: UrcAuthApi,
                    > tonic::server::UnaryService<
                        super::ExchangeApiKeyForUserTokenRequest,
                    > for ExchangeAPIKeyForUserTokenSvc<T> {
                        type Response = super::ExchangeApiKeyForUserTokenResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::ExchangeApiKeyForUserTokenRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UrcAuthApi>::exchange_api_key_for_user_token(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExchangeAPIKeyForUserTokenSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/epic_urc.UrcAuthApi/ExchangeUserTokenForMultiresourceToken" => {
                    #[allow(non_camel_case_types)]
                    struct ExchangeUserTokenForMultiresourceTokenSvc<T: UrcAuthApi>(
                        pub Arc<T>,
                    );
                    impl<
                        T: UrcAuthApi,
                    > tonic::server::UnaryService<
                        super::ExchangeUserTokenForMultiresourceTokenRequest,
                    > for ExchangeUserTokenForMultiresourceTokenSvc<T> {
                        type Response = super::ExchangeUserTokenForMultiresourceTokenResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::ExchangeUserTokenForMultiresourceTokenRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UrcAuthApi>::exchange_user_token_for_multiresource_token(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExchangeUserTokenForMultiresourceTokenSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/epic_urc.UrcAuthApi/CheckUserPermission" => {
                    #[allow(non_camel_case_types)]
                    struct CheckUserPermissionSvc<T: UrcAuthApi>(pub Arc<T>);
                    impl<
                        T: UrcAuthApi,
                    > tonic::server::UnaryService<super::CheckUserPermissionRequest>
                    for CheckUserPermissionSvc<T> {
                        type Response = super::CheckUserPermissionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CheckUserPermissionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UrcAuthApi>::check_user_permission(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CheckUserPermissionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/epic_urc.UrcAuthApi/LookupUserPermissions" => {
                    #[allow(non_camel_case_types)]
                    struct LookupUserPermissionsSvc<T: UrcAuthApi>(pub Arc<T>);
                    impl<
                        T: UrcAuthApi,
                    > tonic::server::UnaryService<super::LookupUserPermissionsRequest>
                    for LookupUserPermissionsSvc<T> {
                        type Response = super::LookupUserPermissionsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LookupUserPermissionsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UrcAuthApi>::lookup_user_permissions(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LookupUserPermissionsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/epic_urc.UrcAuthApi/GetUserInfo" => {
                    #[allow(non_camel_case_types)]
                    struct GetUserInfoSvc<T: UrcAuthApi>(pub Arc<T>);
                    impl<
                        T: UrcAuthApi,
                    > tonic::server::UnaryService<super::GetUserInfoRequest>
                    for GetUserInfoSvc<T> {
                        type Response = super::GetUserInfoResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetUserInfoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UrcAuthApi>::get_user_info(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetUserInfoSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/epic_urc.UrcAuthApi/GetUserId" => {
                    #[allow(non_camel_case_types)]
                    struct GetUserIdSvc<T: UrcAuthApi>(pub Arc<T>);
                    impl<
                        T: UrcAuthApi,
                    > tonic::server::UnaryService<super::GetUserIdRequest>
                    for GetUserIdSvc<T> {
                        type Response = super::GetUserIdResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetUserIdRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UrcAuthApi>::get_user_id(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetUserIdSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/epic_urc.UrcAuthApi/GetProviderUserId" => {
                    #[allow(non_camel_case_types)]
                    struct GetProviderUserIdSvc<T: UrcAuthApi>(pub Arc<T>);
                    impl<
                        T: UrcAuthApi,
                    > tonic::server::UnaryService<super::GetProviderUserIdRequest>
                    for GetProviderUserIdSvc<T> {
                        type Response = super::GetProviderUserIdResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetProviderUserIdRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UrcAuthApi>::get_provider_user_id(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetProviderUserIdSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for UrcAuthApiServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "epic_urc.UrcAuthApi";
    impl<T> tonic::server::NamedService for UrcAuthApiServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
