// This file is @generated by prost-build.
/// A repository addressed by id or by name.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RepositoryRef {
    #[prost(oneof = "repository_ref::Ref", tags = "1, 2")]
    pub r#ref: ::core::option::Option<repository_ref::Ref>,
}
/// Nested message and enum types in `RepositoryRef`.
pub mod repository_ref {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Ref {
        #[prost(bytes, tag = "1")]
        Id(::prost::bytes::Bytes),
        #[prost(string, tag = "2")]
        Name(::prost::alloc::string::String),
    }
}
impl ::prost::Name for RepositoryRef {
    const NAME: &'static str = "RepositoryRef";
    const PACKAGE: &'static str = "lore.access.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.access.v1.RepositoryRef".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.access.v1.RepositoryRef".into()
    }
}
/// A principal's role on a repository. `principal` is a canonical user id
/// (`<idp>:<subject>`) or an email alias; `role` is `read`, `write`, or
/// `admin`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccessGrantRecord {
    #[prost(string, tag = "1")]
    pub principal: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub role: ::prost::alloc::string::String,
}
impl ::prost::Name for AccessGrantRecord {
    const NAME: &'static str = "AccessGrantRecord";
    const PACKAGE: &'static str = "lore.access.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.access.v1.AccessGrantRecord".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.access.v1.AccessGrantRecord".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccessGrantRequest {
    #[prost(message, optional, tag = "1")]
    pub repository: ::core::option::Option<RepositoryRef>,
    #[prost(string, tag = "2")]
    pub principal: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub role: ::prost::alloc::string::String,
}
impl ::prost::Name for AccessGrantRequest {
    const NAME: &'static str = "AccessGrantRequest";
    const PACKAGE: &'static str = "lore.access.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.access.v1.AccessGrantRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.access.v1.AccessGrantRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccessGrantResponse {}
impl ::prost::Name for AccessGrantResponse {
    const NAME: &'static str = "AccessGrantResponse";
    const PACKAGE: &'static str = "lore.access.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.access.v1.AccessGrantResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.access.v1.AccessGrantResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccessRevokeRequest {
    #[prost(message, optional, tag = "1")]
    pub repository: ::core::option::Option<RepositoryRef>,
    #[prost(string, tag = "2")]
    pub principal: ::prost::alloc::string::String,
}
impl ::prost::Name for AccessRevokeRequest {
    const NAME: &'static str = "AccessRevokeRequest";
    const PACKAGE: &'static str = "lore.access.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.access.v1.AccessRevokeRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.access.v1.AccessRevokeRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccessRevokeResponse {
    /// Whether a grant for the principal existed.
    #[prost(bool, tag = "1")]
    pub existed: bool,
}
impl ::prost::Name for AccessRevokeResponse {
    const NAME: &'static str = "AccessRevokeResponse";
    const PACKAGE: &'static str = "lore.access.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.access.v1.AccessRevokeResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.access.v1.AccessRevokeResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccessListRequest {
    #[prost(message, optional, tag = "1")]
    pub repository: ::core::option::Option<RepositoryRef>,
}
impl ::prost::Name for AccessListRequest {
    const NAME: &'static str = "AccessListRequest";
    const PACKAGE: &'static str = "lore.access.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.access.v1.AccessListRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.access.v1.AccessListRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccessListResponse {
    #[prost(message, repeated, tag = "1")]
    pub grants: ::prost::alloc::vec::Vec<AccessGrantRecord>,
}
impl ::prost::Name for AccessListResponse {
    const NAME: &'static str = "AccessListResponse";
    const PACKAGE: &'static str = "lore.access.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.access.v1.AccessListResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.access.v1.AccessListResponse".into()
    }
}
/// Generated client implementations.
pub mod access_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Administration of per-repository access-control grants.
    ///
    /// Served only by servers running server-local authentication (access
    /// control installed); other configurations answer FAILED_PRECONDITION.
    /// Callers must hold the admin role on the target repository (or be server
    /// administrators). Granting on the all-zero repository id manages
    /// server-level grants: an admin grant there confers server administrator.
    #[derive(Debug, Clone)]
    pub struct AccessServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AccessServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AccessServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AccessServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AccessServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Create or replace a principal's grant on a repository.
        pub async fn access_grant(
            &mut self,
            request: impl tonic::IntoRequest<super::AccessGrantRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AccessGrantResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.access.v1.AccessService/AccessGrant",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lore.access.v1.AccessService", "AccessGrant"));
            self.inner.unary(req, path, codec).await
        }
        /// Remove a principal's grant from a repository.
        pub async fn access_revoke(
            &mut self,
            request: impl tonic::IntoRequest<super::AccessRevokeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AccessRevokeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.access.v1.AccessService/AccessRevoke",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lore.access.v1.AccessService", "AccessRevoke"));
            self.inner.unary(req, path, codec).await
        }
        /// List the grants on a repository.
        pub async fn access_list(
            &mut self,
            request: impl tonic::IntoRequest<super::AccessListRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AccessListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.access.v1.AccessService/AccessList",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lore.access.v1.AccessService", "AccessList"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod access_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AccessServiceServer.
    #[async_trait]
    pub trait AccessService: std::marker::Send + std::marker::Sync + 'static {
        /// Create or replace a principal's grant on a repository.
        async fn access_grant(
            &self,
            request: tonic::Request<super::AccessGrantRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AccessGrantResponse>,
            tonic::Status,
        >;
        /// Remove a principal's grant from a repository.
        async fn access_revoke(
            &self,
            request: tonic::Request<super::AccessRevokeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AccessRevokeResponse>,
            tonic::Status,
        >;
        /// List the grants on a repository.
        async fn access_list(
            &self,
            request: tonic::Request<super::AccessListRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AccessListResponse>,
            tonic::Status,
        >;
    }
    /// Administration of per-repository access-control grants.
    ///
    /// Served only by servers running server-local authentication (access
    /// control installed); other configurations answer FAILED_PRECONDITION.
    /// Callers must hold the admin role on the target repository (or be server
    /// administrators). Granting on the all-zero repository id manages
    /// server-level grants: an admin grant there confers server administrator.
    #[derive(Debug)]
    pub struct AccessServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AccessServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AccessServiceServer<T>
    where
        T: AccessService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/lore.access.v1.AccessService/AccessGrant" => {
                    #[allow(non_camel_case_types)]
                    struct AccessGrantSvc<T: AccessService>(pub Arc<T>);
                    impl<
                        T: AccessService,
                    > tonic::server::UnaryService<super::AccessGrantRequest>
                    for AccessGrantSvc<T> {
                        type Response = super::AccessGrantResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AccessGrantRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccessService>::access_grant(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AccessGrantSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.access.v1.AccessService/AccessRevoke" => {
                    #[allow(non_camel_case_types)]
                    struct AccessRevokeSvc<T: AccessService>(pub Arc<T>);
                    impl<
                        T: AccessService,
                    > tonic::server::UnaryService<super::AccessRevokeRequest>
                    for AccessRevokeSvc<T> {
                        type Response = super::AccessRevokeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AccessRevokeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccessService>::access_revoke(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AccessRevokeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.access.v1.AccessService/AccessList" => {
                    #[allow(non_camel_case_types)]
                    struct AccessListSvc<T: AccessService>(pub Arc<T>);
                    impl<
                        T: AccessService,
                    > tonic::server::UnaryService<super::AccessListRequest>
                    for AccessListSvc<T> {
                        type Response = super::AccessListResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AccessListRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AccessService>::access_list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AccessListSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AccessServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "lore.access.v1.AccessService";
    impl<T> tonic::server::NamedService for AccessServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
